# Generated by Django 3.0.5 on 2021-02-14 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminuserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('age', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('address_city', models.TextField(blank=True, null=True)),
                ('address_country', models.TextField(blank=True, null=True)),
                ('address_pincode', models.TextField(blank=True, null=True)),
                ('subscription_from_time', models.DateField()),
                ('subscription_to_time', models.DateField()),
                ('months', models.CharField(default='', max_length=255)),
                ('profile_pic', models.ImageField(null=True, upload_to='profile_pic/', verbose_name='Profile Pic')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserotherloanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=255)),
                ('loan_amount', models.CharField(max_length=255)),
                ('roi_percentage_type', models.CharField(max_length=255)),
                ('roi_percentage', models.CharField(max_length=255)),
                ('other_due_date', models.CharField(max_length=255)),
                ('other_intrest_type', models.CharField(max_length=255)),
                ('loan_duration', models.CharField(max_length=255)),
                ('is_form_four', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminusers.AdminuserModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserincomeCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('income_category_name', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminusers.AdminuserModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserFamilyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('age', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('income', models.CharField(max_length=255)),
                ('goal', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('adminusermodel', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminusers.AdminuserModel')),
            ],
        ),
        migrations.CreateModel(
            name='UsercreditcardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(max_length=255)),
                ('credit_limit', models.CharField(max_length=255)),
                ('charges_and_fees', models.CharField(max_length=255)),
                ('due_date', models.CharField(max_length=255)),
                ('overdue', models.CharField(max_length=255)),
                ('intrest_on_payable', models.CharField(max_length=255)),
                ('payment_made', models.CharField(max_length=255)),
                ('is_form_three', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminusers.AdminuserModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserbankdetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('od_token', models.CharField(max_length=255)),
                ('current_balance', models.CharField(max_length=255)),
                ('intrest_time_period', models.CharField(max_length=255)),
                ('intrest_type', models.CharField(max_length=255)),
                ('intrest_rate', models.CharField(max_length=255)),
                ('is_form_two', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminusers.AdminuserModel')),
            ],
        ),
        migrations.CreateModel(
            name='SubadminauthModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subadmin_email', models.EmailField(max_length=255)),
                ('subadmin_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('subadmin_password', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(null=True, upload_to='profile_pic/', verbose_name='Profile Pic')),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminauth.AdminauthModel')),
            ],
        ),
        migrations.AddField(
            model_name='adminusermodel',
            name='subadmin',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='adminusers.SubadminauthModel'),
        ),
    ]
